#!/usr/bin/env node
/**
 * Refreshes the bundled copy of the Chromium HSTS preload list.
 *
 *   npm run preload:fetch
 *
 * Chromium publishes it as a JSON file in the source tree, served base64-encoded
 * by the git host. It is around fourteen megabytes; what is kept is the host
 * name and whether subdomains are included, which is all the check needs and a
 * fraction of the size.
 *
 * The result is committed. Fetching it at check time would make every report
 * depend on somebody else's uptime, and would tell them every domain anybody
 * looked up here.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE = 'https://chromium.googlesource.com/chromium/src/+/main/net/http/' +
  'transport_security_state_static.json?format=TEXT';

const OUT_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'server', 'data');
const OUT = path.join(OUT_DIR, 'hsts-preload.txt');

console.log('fetching the Chromium preload list…');
const response = await fetch(SOURCE);
if (!response.ok) {
  console.error(`the source answered ${response.status}`);
  process.exit(1);
}

const raw = Buffer.from(await response.text(), 'base64').toString('utf8');

/* The file is JSON with // comments, which JSON.parse will not accept. The
   comments only ever occupy whole lines, so dropping those is enough — and is
   far less fragile than a general comment stripper that has to know about
   strings containing "//". */
const cleaned = raw.split('\n').filter(line => !/^\s*\/\//.test(line)).join('\n');
const data = JSON.parse(cleaned);

const entries = (data.entries || [])
  .filter(entry => entry.name && entry.mode === 'force-https')
  .map(entry => `${entry.name.toLowerCase()}\t${entry.include_subdomains ? '1' : '0'}`)
  .sort();

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT, [
  '# Chromium HSTS preload list, entries with mode=force-https.',
  '# <host>\\t<1 if subdomains are included>',
  `# Generated by scripts/fetch-preload.js — ${entries.length} entries.`,
  ...entries,
  '',
].join('\n'));

console.log(`wrote ${entries.length} entries to ${path.relative(process.cwd(), OUT)}`);
